[database]
url = "mysql://user:password@localhost:3306/unified_eval"

[redis]
url = "redis://localhost:6379"
queue_key = "runs:queue"
dlq_key = "runs:dlq"

[queues]
max_parallel_jobs = 2
max_parallel_gpu_jobs = 1
max_gpus_total = 1

[integrations]
third_party_root = "./third_party"

[clickhouse]
url = "http://localhost:8123"
database = "unified_eval"
username = "default"
password = ""
samples_table = "runs_samples"
metrics_table = "runs_metrics"

[object_store]
endpoint = "http://localhost:9000"
region = "us-east-1"
bucket = "unified-eval"
access_key = "minioadmin"
secret_key = "minioadmin"
use_path_style = true

